# Generated by Django 6.0.4 on 2026-04-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("content", models.TextField(blank=True, null=True, verbose_name="Cодержимое")),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="product/image/", verbose_name="Изображение"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("is_publish", models.BooleanField(default=False, verbose_name="Признак Публикации")),
                ("count_views", models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
    ]
