# Generated by Django 6.0.4 on 2026-04-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="preview",
            field=models.ImageField(blank=True, null=True, upload_to="blog/image/", verbose_name="Изображение"),
        ),
    ]
