# Generated by Django 6.0.4 on 2026-05-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_publish",
            field=models.BooleanField(default=False, verbose_name="Признак Публикации"),
        ),
    ]
