# Generated by Django 6.0.4 on 2026-05-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_is_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_publish",
            field=models.BooleanField(default=False, verbose_name="Публикация"),
        ),
    ]
